### PR TITLE
Add support for TypeScript

### PR DESCRIPTION
**Pull request by AnandChowdhary**
I'd love to use `matchit` with TypeScript, and this PR adds support for types.

### CODE REVIEW

**Comment by lukeed** [comment]
Hey @AnandChowdhary, thanks~!

I tweaked the types a bit. Lemme know if they still look okay to you. If so, I'll publish a new version 👍

**Review by AnandChowdhary — COMMENTED** [review]
Looks great!

**Comment by lukeed** [comment]
Thanks!

**Comment by lukeed** [comment]
Available in 1.1.0

**Pull request merged**
